dbg gha

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -45,28 +45,51 @@ jobs:
     #  options: --user vscode --privileged --cpus 4 --memory 8g --workdir ${{ github.workspace }}
 
     steps:
-    - name: Run shell script
+    - name: Ammend Environment Variables
+      id: environment
       run: |
-        set -ex;\
+        echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F [\/] '{print $1}')" | tee -a ${GITHUB_ENV};\
+
+    - name: dbg1
+      id: dbg1
+      run: |
         echo "-----------------------------------";\
+        echo;\
+        echo dbg1.0
+        git status || true;\
+        echo "whoami = $(whoami);\
+        echo "groups = $(groups);\
+        echo "[user_id:group] [$(id -u):$(id -g)]";\
+        cat /etc/passwd | grep $(whoami);\
+        sudo tree -a $WORKSPACE || true;\
+        echo;
+        echo "-----------------------------------";\
+        echo;\
+        echo dbg1.1;\
+        pwd;\
+        echo;\
+        ls -lah . ;\
+        echo;\
+        ls -lah .. ;\
+        echo;\
+        tree . -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
+        tree .. -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
+        echo dbg1.3
         cd $WORKSPACE;\
         pwd;\
-        git status || true;\
-        ls -lah;\
-        tree .;\
-        groups;\
-        echo "-----------------------------------";\
-        echo "user_id:group $(id -u):$(id -g)";\
-        whoami;\
-        cat /etc/passwd | grep $(whoami);\
-        echo "-----------------------------------";\
-        sudo tree -a $WORKSPACE || true;\
-        sudo chown -R $USER:$USER $WORKSPACE/* || true;\
-        pwd;\
-        git status || true;\
-        ls -lah;\
-        echo;
+        echo;\
+        ls -lah . ;\
+        echo;\
+        ls -lah .. ;\
+        echo;\
+        tree . -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
+        tree .. -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
 
+      # #sudo chown -R $USER:$USER $WORKSPACE/* || true;\
       #               #sudo tree -a /home/github/actions-runner/_w || true;\
       #               #sudo chown -R $USER:$USER /home/github/actions-runner/_w/* || true;\
       #               #sudo tree -a /home/github/actions-runner/_work || true;\
@@ -74,87 +97,160 @@ jobs:
     - name: Git Checkout
       uses: actions/checkout@v4
       with:
-        repository: ${{ github.repository }}
-        path: ''
-        clean: 'true'
-        fetch-depth: '1'
-        fetch-tags: 'true'
-        submodules: 'recursive'
         # Add repository path as safe.directory for Git global config by running `git
         # config --global --add safe.directory <path>`
+        repository: ${{ github.repository }}
         set-safe-directory: 'true'
-    - name: Run shell script
-      run: set -ex; pwd; git status || true; ls -lah; whoami; groups
+        fetch-depth: '1'
+        submodules: 'recursive'
+        fetch-tags: 'true'
+        clean: 'true'
+        path: ${{ github.workspace }}
 
-    - name: Git Checkout
-      uses: actions/checkout@v4
-      id: git
-
-    - name: Create Kind Cluster
-      id: kind-create-cluster-cilium
+    - name: dbg2
+      id: dbg2
       run: |
-        set -ex
-        direnv allow
-        sudo docker volume ls
-        sudo docker volume create cilium-control-plane-n01
-        sudo docker volume create cilium-worker-n01
-        sudo docker volume create cilium-worker-n02
-        sudo docker volume ls
-        sudo kind delete cluster --name cilium
-        sleep 5;
-        sudo kind create cluster --name cilium --config hack/kind.yaml --wait 1m || true
-        sudo kind get kubeconfig --name cilium > $KUBECONFIG
-        sleep 30;
-        kubectl --kubeconfig .kube/config get po -owide -A
+        echo "-----------------------------------";\
+        echo;\
+        echo dbg2.0
+        git status || true;\
+        echo "whoami = $(whoami);\
+        echo "groups = $(groups);\
+        echo "[user_id:group] [$(id -u):$(id -g)]";\
+        cat /etc/passwd | grep $(whoami);\
+        sudo tree -a $WORKSPACE || true;\
+        echo;
+        echo "-----------------------------------";\
+        echo;\
+        echo dbg2.1;\
+        pwd;\
+        echo;\
+        ls -lah . ;\
+        echo;\
+        ls -lah .. ;\
+        echo;\
+        tree . -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
+        tree .. -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
+        echo dbg2.2
+        cd $WORKSPACE;\
+        pwd;\
+        echo;\
+        ls -lah . ;\
+        echo;\
+        ls -lah .. ;\
+        echo;\
+        tree . -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
+        tree .. -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
 
-      #       -
-      #           name: Provision KinD Cluster
-      #           uses: helm/kind-action@v1.8.0
-      #           with:
-      #               config: hack/kind.yaml
-      #               install_only: true
-      #               cluster_name: cilium
-      #               wait: true
-
-    - name: Pulumi Setup
-      id: pulumi-up
+    - name: dbg3
+      id: dbg3
       run: |
-        set -ex
-        direnv allow
-        pwd
-        sudo kind get kubeconfig --name cilium > $KUBECONFIG
-        pulumi login --local
-        pulumi stack init iac-mesh-pac
-        pulumi stack select iac-mesh-pac
-        pulumi install
-        pulumi up --yes --skip-preview
-        sleep 30
-        kubectl --kubeconfig .kube/config get po -owide -A
-        sleep 30
-        kubectl --kubeconfig .kube/config get po -owide -A
+        sudo chown -R $USER:$USER $WORKSPACE/* || true;\
+        echo "-----------------------------------";\
+        echo;\
+        echo dbg3.0
+        git status || true;\
+        echo "whoami = $(whoami);\
+        echo "groups = $(groups);\
+        echo "[user_id:group] [$(id -u):$(id -g)]";\
+        cat /etc/passwd | grep $(whoami);\
+        sudo tree -a $WORKSPACE || true;\
+        echo;
+        echo "-----------------------------------";\
+        echo;\
+        echo dbg3.1;\
+        pwd;\
+        echo;\
+        ls -lah . ;\
+        echo;\
+        ls -lah .. ;\
+        echo;\
+        tree . -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
+        tree .. -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
+        echo dbg2.2
+        cd $WORKSPACE;\
+        pwd;\
+        echo;\
+        ls -lah . ;\
+        echo;\
+        ls -lah .. ;\
+        echo;\
+        tree . -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
+        tree .. -a -I .git -I .devcontainer -I node_modules;\
+        echo;\
 
-    - name: Cilium Status
-      id: cilium-status
-      run: |
-        set -ex
-        direnv allow
-        pwd
-        sudo kind get kubeconfig --name cilium > .kube/config
-        kubectl --kubeconfig .kube/config get po -owide -A
-        cilium status --wait --wait-duration 3m
-        sleep 30
-        kubectl --kubeconfig .kube/config get po -owide -A
+#   - name: Create Kind Cluster
+#     id: kind-create-cluster-cilium
+#     run: |
+#       set -ex
+#       direnv allow
+#       sudo docker volume ls
+#       sudo docker volume create cilium-control-plane-n01
+#       sudo docker volume create cilium-worker-n01
+#       sudo docker volume create cilium-worker-n02
+#       sudo docker volume ls
+#       sudo kind delete cluster --name cilium
+#       sleep 5;
+#       sudo kind create cluster --name cilium --config hack/kind.yaml --wait 1m || true
+#       sudo kind get kubeconfig --name cilium > $KUBECONFIG
+#       sleep 30;
+#       kubectl --kubeconfig .kube/config get po -owide -A
 
-    - name: Cleanup
-      run: |
-        set -ex
-        direnv allow
-        sudo kind delete cluster --name cilium
-        sudo docker volume ls
-        #sudo docker volume rm cilium-control-plane-n01
-        #sudo docker volume rm cilium-worker-n01
-        #sudo docker volume rm cilium-worker-n02
-        #sudo docker volume ls
+#     #       -
+#     #           name: Provision KinD Cluster
+#     #           uses: helm/kind-action@v1.8.0
+#     #           with:
+#     #               config: hack/kind.yaml
+#     #               install_only: true
+#     #               cluster_name: cilium
+#     #               wait: true
+
+#   - name: Pulumi Setup
+#     id: pulumi-up
+#     run: |
+#       set -ex
+#       direnv allow
+#       pwd
+#       sudo kind get kubeconfig --name cilium > $KUBECONFIG
+#       pulumi login --local
+#       pulumi stack init iac-mesh-pac
+#       pulumi stack select iac-mesh-pac
+#       pulumi install
+#       pulumi up --yes --skip-preview
+#       sleep 30
+#       kubectl --kubeconfig .kube/config get po -owide -A
+#       sleep 30
+#       kubectl --kubeconfig .kube/config get po -owide -A
+
+#   - name: Cilium Status
+#     id: cilium-status
+#     run: |
+#       set -ex
+#       direnv allow
+#       pwd
+#       sudo kind get kubeconfig --name cilium > .kube/config
+#       kubectl --kubeconfig .kube/config get po -owide -A
+#       cilium status --wait --wait-duration 3m
+#       sleep 30
+#       kubectl --kubeconfig .kube/config get po -owide -A
+
+#   - name: Cleanup
+#     run: |
+#       set -ex
+#       direnv allow
+#       sudo kind delete cluster --name cilium
+#       sudo docker volume ls
+#       #sudo docker volume rm cilium-control-plane-n01
+#       #sudo docker volume rm cilium-worker-n01
+#       #sudo docker volume rm cilium-worker-n02
+#       #sudo docker volume ls
 
 #       -
 #           name: Pulumi Preview
